# Generated by Django 5.0.3 on 2024-03-15 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataBuild', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speedbreakerdata',
            name='lat',
            field=models.FloatField(max_length=9, verbose_name='Latitutude'),
        ),
        migrations.AlterField(
            model_name='speedbreakerdata',
            name='long',
            field=models.FloatField(max_length=9, verbose_name='Latitutude'),
        ),
    ]
